"""Update Address Table

Revision ID: 239f5fd9f4bc
Revises: 
Create Date: 2025-07-13 10:30:58.469782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '239f5fd9f4bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_city', sa.String(length=256), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_column('address_city')

    # ### end Alembic commands ###
